version: '3.5'

services:
  bot:
    container_name: parkun_bot
    networks:
      - proxynet
    build:
      context: ../
      dockerfile: Dockerfile
    restart: always
    volumes:
      - /tmp/temp_files_parkun:/tmp/temp_files_parkun
      - ./parkun_bot/config:/tmp/parkun_config
    depends_on:
      - redis
      - rabbit
