version: '3.5'

volumes:
  redis-data:

services:
  redis:
    volumes:
      - redis-data:/data

  rabbit:
    volumes:
      - rabbit-data:/var/lib/rabbitmq

  wiremock:
    container_name: parkun_wiremock
    image: rodolpheche/wiremock:2.25.0-alpine
    networks:
      - proxynet
    ports:
      - 18080:8080
    volumes:
      - wiremock-data:/home/wiremock
      - ./wiremock/mappings:/home/wiremock/mappings
