version: '3.5'

volumes:
  wiremock-data:
  rabbit-data:

networks:
  proxynet:
    name: parkun

services:
  redis:
    container_name: parkun_redis
    image: redis:5.0.7-alpine
    command: redis-server --requirepass 'redis' --appendonly yes
    ports:
      - 16379:6379
    volumes:
      - /home/parkun/redis_data:/data
    restart: always
    networks:
      - proxynet

  rabbit:
    container_name: parkun_rabbit
    networks:
      - proxynet
    ports:
      - 5672:5672
      - 15672:15672
    build:
      context: ./rabbitmq
      dockerfile: Dockerfile
    volumes:
      - /home/parkun/rabbit_data:/var/lib/rabbitmq
    restart: always
    hostname: parkun_rabbit
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:15672"]
      interval: 30s
      timeout: 10s
      retries: 5
